name: Import SARIF
on:
  push:
    branches: [ master, v1 ]

jobs:
  Import-SARIF:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SCW Training (dir)
        uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@versionbumps-and-test
        with:
          inputSarifFile: sarif/
          outputSarifFile: processed-sarifs
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Import Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: processed-sarifs

